### ISSUE TITLE
请问能否调整涂鸦笔画的优化程度

### ISSUE THREAD

**Issue by pisceswb** [BryceAndJuly/Whiteboard#11]
当前笔画的平滑优化程度，在电脑端使用很好，但在华为平板端优化的太厉害了，请问有办法自定义平滑等级吗？

**Comment by BryceAndJuly** [comment]
使用文档里有个更改画笔粗细的：

---

### 1、手动更改画笔的粗细

对于版本V1.1.0，打开挂件文件夹`Whiteboard`——`assets`——`index-7cc5d345.js`,在该js文件中搜索：

```css
simulatePressure:e.simulatePressure,size:e.strokeWidth*1.2,thinning
```

---

更完整一点是：

```js
n={simulatePressure:e.simulatePressure,size:e.strokeWidth*1.2,thinning:.6,smoothing:.5,streamline:.5,easing:r=>Math.sin(r*Math.PI/2),last:!!e.lastCommittedPoint}
```

那个平滑度的默认值是0.5

```js
smoothing:.5,
```

你可以0.1到0.9都试试看啥效果，比如：

```js
smoothing:0.1,
```


改完之后记得保存，然后就是清一下缓存或者重启一下软件，防止它一直加载缓存好的旧文件。应该就能生效了。

**Comment by pisceswb** [comment]
实际测试发现，仅粗细可调(明显)，压感和平滑都不可调呢(调整前后没有变化)

**Comment by BryceAndJuly** [comment]
那个就是关闭压感的，调整前后感觉变化不大是因为压感对笔画的影响参数【thinning:.6】本来就调的不大，你把它设置成【thinning:.9】之后，开关压感的变化就很明显了。手写的几个调节参数都在这里了，你自己调调看吧，手写方面我也不太了解。
**开启压感的效果：**

https://github.com/BryceAndJuly/Whiteboard/assets/58081876/d7a86e98-caf0-497e-aecb-4186b987ecfa


**关闭压感的效果：**

https://github.com/BryceAndJuly/Whiteboard/assets/58081876/5455ccd4-0b21-4278-bf9a-d9aa52f67dac
