### ISSUE TITLE
预览文档中的嵌入块渲染问题

### ISSUE THREAD

**Issue by AvoidantPerDis** [BryceAndJuly/Whiteboard#12]
还是有继续渲染的需求的，可以告知为什么不继续渲染吗？

**Comment by BryceAndJuly** [comment]
有时间可以研究一下

**Comment by BryceAndJuly** [comment]
待会发布的V1.2.0是支持渲染嵌入块的
![update](https://github.com/BryceAndJuly/Whiteboard/assets/58081876/5eaf2fe0-9c9d-45c9-8e50-5f0d03e2fb5a)
