### ISSUE TITLE
疑问：这个挂件怎么从全屏切换成 iframe 模式呢？

### ISSUE THREAD

**Issue by winter60** [BryceAndJuly/Whiteboard#14]
因为这个问题下载过两三次，也卸载过两三次这个挂件。所以，还是来问一下大佬，使用了该挂件后，如何从全屏模式切换成 iframe 挂件块的形式，让挂件和文档内其他块同时显示。

**Comment by BryceAndJuly** [comment]
现在白板的这个全屏是通过直接设置样式硬凑出来的，你打开`Whiteboard`——`index.html`，看一下开头那里就能看到了。把设置样式的几行删掉应该就能换成默认的挂件形式了。
![挂件全屏](https://github.com/BryceAndJuly/Whiteboard/assets/58081876/64a25b21-1d9e-4533-b916-436a1d8df37a)

**Comment by winter60** [comment]
@BryceAndJuly 其实有时候全屏也挺方便的,  所以建议出一个切换的方式（比如在挂件内增加一个按钮），在全屏模式和挂件模式相互切换，因为他们都有各自的场景。 
 

可以参考drawio 挂件 
![image](https://github.com/BryceAndJuly/Whiteboard/assets/23653326/c2d6705c-f959-43f5-88bf-412dd5f7767a)

或者自定义块样式插件
![image](https://github.com/BryceAndJuly/Whiteboard/assets/23653326/1c7e0f47-caf1-4504-8db4-46b7f8708db4)

**Comment by BryceAndJuly** [comment]
不太合适，之前搞自动设置别名、添加CSS代码片段来隐藏标题、建议用户在空白的文档上嵌入该白板而不是有内容的文档，就是想减少打开白板时页面的闪烁。如果文档里还有其他内容，那么到时候打开时会先出现文档，然后才是铺满白板，看着很难受的。

像文档内绘制图表的场景，个人感觉集市上另外一个Excalidraw挂件做的更好，它是直接渲染成图片，在导出PDF之类格式的也能直接导出，比这个更合适。
