### ISSUE TITLE
能否增加对Latex的支持

### ISSUE THREAD

**Issue by lqucool** [BryceAndJuly/Whiteboard#15]
支持latex数学公式的输入真的非常有用，可否增加这项功能。
可以参考excalidraw中对latex的支持，https://math.preview.excalidraw.com/

**Comment by BryceAndJuly** [comment]
现在也可以啊。白板支持嵌入思源笔记绝大部分的块，而思源的块支持Latex公式，那就相当于能在白板里嵌入公式了。再加上思源的编辑器用起来体验还可以，实在没必要费大劲去给白板另外加上Latex。

https://github.com/BryceAndJuly/Whiteboard/assets/58081876/2149d447-eba1-454b-a741-34874c6f51cc
