### ISSUE TITLE
嵌入网页以后，可以为网页调整图层吗

### ISSUE THREAD

**Issue by linda1116** [BryceAndJuly/Whiteboard#16]
尝试了一下，嵌入网页后，添加图形、箭头都是在网页的下面，通过图层调整以后好像没有变化。

我是通过这个把笔记中的块添加进来，在这个基础上做一些图形标注，不知道能不能实现这个效果。

**Comment by BryceAndJuly** [comment]
* [https://github.com/excalidraw/excalidraw/pull/6691](https://github.com/excalidraw/excalidraw/pull/6691)
* [https://github.com/excalidraw/excalidraw/issues/6830#issuecomment-1657839679](https://github.com/excalidraw/excalidraw/issues/6830#issuecomment-1657839679)

这个已知缺陷了。Excalidraw作者跟PR这个功能的大叔也说了，目前的设计就是IFrame放在顶层。
![1](https://github.com/BryceAndJuly/Whiteboard/assets/58081876/be5d88be-737d-497d-855c-1a2702e1ed46)
![2](https://github.com/BryceAndJuly/Whiteboard/assets/58081876/e76bd2a5-5ecc-421c-ad71-c73583b3edfd)

即便如此，你还是可以稍微改动一下来实现在iframe中标注的效果，但似乎有点副作用。

## 如何修改？

1、打开挂件所在文件夹，找到对应的CSS文件

```css
Whiteboard/assets/index-8a263e3d.css
```

在最后加上

```css
.excalidraw__embeddable-container {
    z-index: inherit;
}
```

改完之后记得保存文件，然后笔记软件清一下缓存或者重启一下应该就能生效了。

2、为了IFrame不被遮挡，画布的背景要设置成透明的
![3](https://github.com/BryceAndJuly/Whiteboard/assets/58081876/70138728-825b-4a29-bf86-1d212d5d0298)

## 已知的副作用有

* iframe无法使用滚动，所以需要调整iframe框的大小来铺开全部内容
* 画板无法设置其他背景色，只能设置成透明的，否则iframe会被遮挡。
* 标注后，无法隔着iframe选中标注，标注后不方便二次修改——解决的办法是使用鼠标的右键菜单中的【锁定】功能来锁定要标注的iframe。

https://github.com/BryceAndJuly/Whiteboard/assets/58081876/7fe47f3e-e298-4f71-87a6-e0c91fa0c181

**Comment by linda1116** [comment]
感谢，修改步骤写的详细，已经达到视频里的效果
