### ISSUE TITLE
功能请求：当使用手写笔时，更改鼠标形状

### ISSUE THREAD

**Issue by pisceswb** [BryceAndJuly/Whiteboard#17]
请问作者能否修改一下手写状态时的鼠标形状，当前为十字形，手写落笔和抬笔时，十字形在不停的隐藏和显示，影响视线，请问能否将其修改为一个小圆点，谢谢！

另经过长时间测试，将下面的代码内容修改后，成功实现了PC端手写(Wacom)和平板端手写(华为平板)都能处于一个可接受程度的手写笔状态，分享一下。

修改前：
`n={simulatePressure:e.simulatePressure,size:e.strokeWidth*1.2,thinning:.6,smoothing:.5,streamline:.5,easing:r=>Math.sin(r*Math.PI/2),last:!!e.lastCommittedPoint}`

修改后：
`n={simulatePressure:e.simulatePressure,size:e.strokeWidth*1.6,thinning:0,smoothing:1,streamline:0,easing:r=>Math.sin(r*Math.PI/2),last:!!e.lastCommittedPoint}`

**Comment by pisceswb** [comment]
在一个白板页面中，手写笔记内容较多时，平板端继续手写会非常有明显的卡顿现象。字迹越多，卡顿越严重。

**Comment by pisceswb** [comment]
如果将鼠标显示为小圆点不好实现的话，将手写时的鼠标形状隐藏或完全透明，使其不可见也行。

**Comment by BryceAndJuly** [comment]
不太清除手写笔的情况，我在电脑上用鼠标画的时候，那个鼠标的十字型图标是一直显示的，没有出现不停的隐藏和显示这种情况。

不过要改手写时的图标也是可以的，找到挂件文件夹，打开

```css
Whiteboard/assets/index-c894b550.js
```

搜索：

```css
{TEXT:"text",CROSSHAIR:"crosshair"
```


要将十字型图标改成指针型图标的话，可以改成这样：

```css
{TEXT:"text",CROSSHAIR:"default"
```


要将十字型图标改成小手型图标的话，可以改成这样：

```css
{TEXT:"text",CROSSHAIR:"pointer"
```

具体可以参考：[https://developer.mozilla.org/zh-CN/docs/Web/CSS/cursor](https://developer.mozilla.org/zh-CN/docs/Web/CSS/cursor)

**Comment by pisceswb** [comment]
谢谢，修改为{TEXT:"text",CROSSHAIR:"none"，就不显示光标了。不过这种形式可能只适合手写笔用，因为用鼠标时，也不显示指针位置。
