### ISSUE TITLE
同步缺陷反馈

### ISSUE THREAD

**Issue by pisceswb** [BryceAndJuly/Whiteboard#18]
反馈一个同步小缺陷，
当同时开启PC端思源笔记和Android端思源笔记时，在任意一端增加了手写内容，并同步到云(思源或webdav)。从另一端同步后，新增加内容，不能正常显示出来。
即便关闭白板页面，重新打开，甚至关闭思源笔记重新打开，也有很大几率不能显示出，在另一端新添加的内容的后半部分。

**Comment by pisceswb** [comment]
遇到显示不全的问题时，重新开关白板页面，不能解决问题。关闭思源笔记重新打开，能够显示全部内容。

**Comment by BryceAndJuly** [comment]
可能受到缓存的影响吧

**Comment by BryceAndJuly** [comment]
下次碰到这种情况，试着手动清理一下缓存试试：
![清理缓存](https://github.com/BryceAndJuly/Whiteboard/assets/58081876/273d9f0e-5ef4-4191-bf25-c00fb4f6176f)

**Comment by pisceswb** [comment]
才注意到，页面右上角有一个刷新按钮，同步完成后，点击一下刷新按钮就能够正常显示了
