### ISSUE TITLE
手写笔记较多时，Android端会发生严重卡顿

### ISSUE THREAD

**Issue by pisceswb** [BryceAndJuly/Whiteboard#19]
在一个白板页面中，手写笔记内容较多时，平板端继续手写会非常有明显的卡顿现象。字迹越多，卡顿越严重。

请问是否是，将页面上的所有手写笔记都加载的原因？
能否局部加载显示可见页面部分的手写笔记内容，随可见页面的移动，动态加载所需内容？

谢谢！

**Comment by BryceAndJuly** [comment]
> 请问是否是，将页面上的所有手写笔记都加载的原因？

这个我也不太清楚，原仓库的代码我并不是全部看过的，只看了要修改的那部分。但是我记得手写方面我只改了一下画笔粗细的值，没动其他的，按理说手写方面应该能有原库的性能水平的。

**Comment by pisceswb** [comment]
哦，那可能原代码就可能会造成卡顿现象。

**Comment by BryceAndJuly** [comment]
这个目前搞不来，太费时间了，关了关了。
