### ISSUE TITLE
能否实现自动保存

### ISSUE THREAD

**Issue by pisceswb** [BryceAndJuly/Whiteboard#2]
请问能否实现自动保存功能，以防止数据的意外丢失。具体为：
1. 切换页面，离开whiteboard后，自动保存。
2. 关闭思源笔记时，自动保存。

感谢作者提供这么好的挂件！👍

**Comment by BryceAndJuly** [comment]
可以让它在发生编辑之后延时几秒自动保存，这个影响不大，晚些时候再弄吧。

**Comment by BryceAndJuly** [comment]
新版已经发布了——[https://github.com/BryceAndJuly/Whiteboard/releases/tag/V1.0.3](https://github.com/BryceAndJuly/Whiteboard/releases/tag/V1.0.3)

如果有问题，再提新的Issue即可，这个先关掉了。

**Comment by pisceswb** [comment]
非常好用，赞！👍👍👍

**Comment by pisceswb** [comment]
保存提示确实有点分散注意力，请问能否保留自动保存的功能，而不显示“已保存”的提示。只有保存意外失败时，才弹窗提示

**Comment by BryceAndJuly** [comment]
反正刚好有空，顺便就改一下吧，等会发个版本。
