### ISSUE TITLE
请问怎么能够取消或减弱手写笔笔画的自动补全效果

### ISSUE THREAD

**Issue by pisceswb** [BryceAndJuly/Whiteboard#20]
当前手写时，会自动补全部分笔画成圆形，如下图。请问怎样能取消或减弱这种自动补全功能呢，谢谢！
![image](https://github.com/BryceAndJuly/Whiteboard/assets/104658457/d38aa89d-be1c-4d51-9cd8-2ab92c781350)

**Comment by BryceAndJuly** [comment]
写多少就是多少，没发现什么自动补全功能。

https://github.com/BryceAndJuly/Whiteboard/assets/58081876/a7af7878-2d1f-4905-8c02-ec89cae221e9
