### ISSUE TITLE
关于「素材库」文件夹内资源的识别

### ISSUE THREAD

**Issue by QMike0** [BryceAndJuly/Whiteboard#21]
首先感谢佬开发这个挂件，弥补了当前思源白板功能的缺失。
问题如下：
在Excalidraw中下载素材后，library文件夹和里面的文件都会被思源识别为「未引用的资源文件」，如下图所示：
![image](https://github.com/BryceAndJuly/Whiteboard/assets/43239563/e0c794a8-695e-43ec-8272-ec5a07b6dbf4)
猜想是因为将素材库文件夹存储于`assets`文件夹中所致，能否将library文件夹路径调整到`/data/public`或`/data/storage/petal`中，这样应该就不会出现该情况，避免误删素材。
另外现在初次点击该选项还需要手动在资源管理器中定位到library文件夹中，能否每次点击白板中的「素材库」按钮时默认打开该文件夹。

**Comment by BryceAndJuly** [comment]
这个白板挂件中素材库的内容是保存到`LocalStorage`中的，不是`assets/ExcalidrawFiles`文件夹里的某个文件，所以不会创建默认的`library`文件夹，也不会初次点击默认定位到`library`文件夹中。

如果想让下载好的素材库文件随笔记一起同步，可以把文件放到你刚刚提到的`/data/public`路径之类的。你手动把下载的素材库文件放到`assets/ExcalidrawFiles`里而且没有被引用，肯定会被标记成`未引用资源`的。
![存储](https://github.com/BryceAndJuly/Whiteboard/assets/58081876/3895061e-5dde-4b9c-91ad-0d658146b65b)
![截图](https://github.com/BryceAndJuly/Whiteboard/assets/58081876/cb9f1d2d-9037-41a3-b081-db86e6a7dfd1)

**Comment by QMike0** [comment]
了解，谢谢解答~
