### ISSUE TITLE
嵌入块的时候白板中有画图内容的区域缩小满屏体现

### ISSUE THREAD

**Issue by HopeLHP** [BryceAndJuly/Whiteboard#24]
有时候嵌入块的时候发现区域内没有内容，内容在显示区域以外，需要滚动到内容区域挺不方便的，希望能嵌入的时候预先将画图内容聚焦满屏体现

**Comment by BryceAndJuly** [comment]
* 白板当前区域内没有内容的话，点一下【滚动回到内容】按钮就能滚动到内容区域了，操作并不算繁琐。
* 至于缩放，Excalidraw本来的交互就挺好的，可以根据自己需要在10%~3000%范围内设置缩放比例，然后在该比例下通过拖拽嵌入文档，为什么要写死成缩小呢？

https://github.com/BryceAndJuly/Whiteboard/assets/58081876/bb5581e2-38e6-4373-8ddf-f1b7434f9b82

**Comment by HopeLHP** [comment]
我可能没表达清楚，我把铺满excalidraw挂件的文档叫做挂件文档，就是我的场景是在正文中嵌入挂件文档块的时候，嵌入块的内容展示会和挂件文档的内容展示位置相同，也就是说如果挂件文档中内容比较偏离的话，嵌入块内容也是偏离的。
我想达到的效果是，obsidian在正文引用excalidraw的样子类似于一种导出完整内容的图片展示在正文中，而不是一个可以随意偏离内容区域的块，也就是说希望在思源中可以实现在嵌入块的时候，就能在正文中展示完整内容（因为比较已经嵌入到正文中了，或者被其他文档引用了，肯定是希望展示完整内容的）。
如图：
![image](https://github.com/BryceAndJuly/Whiteboard/assets/70339118/9c5733ba-44d2-4ed9-a21b-6fd3c57393a9)
![image](https://github.com/BryceAndJuly/Whiteboard/assets/70339118/ef478768-177d-40cd-aec8-58c9a0a06328)

**Comment by HopeLHP** [comment]
> * 白板当前区域内没有内容的话，点一下【滚动回到内容】按钮就能滚动到内容区域了，操作并不算繁琐。

你说得滚动回到内容的按钮只能到达回到内容区域，但是不能达到回到内容区域并展示全部内容区域（如果内容比较或者多的时候）

**Comment by BryceAndJuly** [comment]
那就在挂件嵌入块里调好位置后点击【保存】就行了，保存时会记住当前位置和缩放比例的。原画板和后续其他嵌入块都会使用这个比例和位置。

https://github.com/BryceAndJuly/Whiteboard/assets/58081876/71fcb8b9-802e-4bba-9ab2-7dcc37037da2

**Comment by BryceAndJuly** [comment]
刚才光注意那个位置偏离的问题了。显示完整内容的话，推荐集市里另外一个Excalidraw挂件，它简直就是给文档内嵌入绘图这个场景量身定做的，非常合适。

**Comment by HopeLHP** [comment]
集市里的挂件插件其实都用过，最终效果上，你的方案应该是最好的且巧妙的，插件不能引用，另一个挂件得单独打开编辑而且不能统一管理。
上面你说保存，我目前是这么做的，其实我是觉得编辑和文档引用得分开来看，编辑的时候是局部的，引用的时候是整体的，如果在编辑完后再回到显示全部内容后保存（得手动缩放调整，其实也挺麻烦），体验上总感觉差点意思。
当然这个挂件已经解决了引用和统一管理两个最重要的问题，其他问题也能克服克服。

**Comment by BryceAndJuly** [comment]
其实不用回到原画板保存，我说的【保存】是在引用那里直接调整位置、比例后直接点保存。
不管是原画板还是引用，它们读取的都是同一个文件，所以在一处改了之后，原画板和该画板的所有引用都会同步更改（刷新后就能看到变更）

**Comment by HopeLHP** [comment]
对了，还有个点我就不单开issue了，其实都是一些体验的细节。
因为挂件得先新建一个文档然后在文档中插入挂件嘛，不知道可不可以通过插件，点击右上角的插件按钮就自动在问个笔记本的指定新建一个文档并插入挂件，这样减少一些步骤。

**Comment by BryceAndJuly** [comment]
这个还没试过，后面有时间可以试试。我还是比较期待官方的白板，内置的功能总比第三方的融合的好，就是进度太慢了，等得实在没有耐心了才用挂件的方案。

**Comment by HopeLHP** [comment]
官方白板如果要出的话，我估计是走ob的canvas的路，我倒觉得和excalidraw是两条路，canvas是偏向于内容块的组织的，类似于heptabase，excalidraw是偏向于画图和手写的+轻内容组织。
我觉得你这个挂件可以顶半边天了，本来都在ob上用excalidraw的，有你这个之后，我就迁回来了，官方出完白板之后，思源就齐活了。
再次感谢
