### ISSUE TITLE
素材库功能

### ISSUE THREAD

**Issue by AkiaHaha** [BryceAndJuly/Whiteboard#28]
你好，素材库功能开发好了吗？
下载使用白板近半年了，一直不能成功导入外部的pdf或者图片之类的资源，显示内容如图所示[
![Snipaste_2024-09-14_11-15-26](https://github.com/user-attachments/assets/a730858f-ac85-4328-b9fd-5f0797d4375e)
](url)

_Originally posted by @AkiaHaha in https://github.com/BryceAndJuly/Whiteboard/issues/22#issuecomment-2350808352_

**Comment by AkiaHaha** [comment]
拖拽外部资源进入白板也无法使用，报错：
无法加载无效的文件

**Comment by BryceAndJuly** [comment]
Excalidraw这个素材库功能可能跟你想的不太一样，一个素材是由单个或多个绘图元素组成的。你可以先到Excalidraw的官网：[https://excalidraw.com/](https://excalidraw.com/)，点击`素材库`——`浏览素材库`去导入和使用一下它的在线素材库来感受一下。素材库文件的后缀一般是`.excalidrawlib`，可以到它的在线素材库下载，也可以自己绘制并添加到素材库然后使用素材库的【保存到】功能保存为素材库文件，方便以后导入。

**Comment by AkiaHaha** [comment]
> Excalidraw这个素材库功能可能跟你想的不太一样，一个素材是由单个或多个绘图元素组成的。你可以先到Excalidraw的官网：https://excalidraw.com/，点击`素材库`——`浏览素材库`去导入和使用一下它的在线素材库来感受一下。素材库文件的后缀一般是`.excalidrawlib`，可以到它的在线素材库下载，也可以自己绘制并添加到素材库然后使用素材库的【保存到】功能保存为素材库文件，方便以后导入。

非常感谢!!!
