### ISSUE TITLE
能不能只把它当个嵌入的白板，还能退出继续编辑内容呢？

### ISSUE THREAD

**Issue by Mowen-M** [BryceAndJuly/Whiteboard#29]
现在打开了之后，文档就没法用了，无法返回文档，这样管理会比较混乱，，希望加个退出挂件的按钮

**Comment by Mowen-M** [comment]
有的时候并不想将整个文档都变成白板，这样，还要去正文的文档引用这个白板来达到链接的作用，希望加一个block，来限制大小在文档中，就像别的挂件一样

**Comment by BryceAndJuly** [comment]
这个挂件只适合在空白文档中嵌入，就像挂件说明中写的那样。文档中已经写有其他内容的话就不要直接嵌入这个挂件了，会遮挡其他内容。

其他文档对白板的引用，我一般是用嵌入块，或者麻烦一点用引用块+图片。其实如果是文档内绘图，集市里另外一款Excalidraw挂件会更适合你。
![空白文档](https://github.com/user-attachments/assets/9152fafd-cfb3-4039-873e-6755bb2a4b55)

https://github.com/user-attachments/assets/8db75d5d-ae0f-4ffc-b598-8dcefb94910a

**Comment by banjuer** [comment]
> 挂件只适合在空白文档中嵌入，就像挂件说明中写的那样。文档中已经写有其他内容的话就不要直接嵌入这个挂件了，会遮挡其他内容。
> 
> 其他文档对白板的引用，我一般是用嵌入块，或者麻烦一点用引用块+图片。其实如果是

不小心在文档内创建了如何还原呢，用思源的历史吗

**Comment by BryceAndJuly** [comment]
> 不小心在文档内创建了如何还原呢，用思源的历史吗

@banjuer 不用这么麻烦，用挂件的块标菜单来删除就可以了。可以参考：[https://github.com/BryceAndJuly/Whiteboard/issues/48](https://github.com/BryceAndJuly/Whiteboard/issues/48)
