### ISSUE TITLE
拖进来的嵌入块适配深色模式

### ISSUE THREAD

**Issue by DIDAO123** [BryceAndJuly/Whiteboard#33]
嵌入块拖进来后背景一直是白色的，在深色模式下比较突兀，希望可以跟挂件当前状态或者思源主题状态进行调节，或者手动调节也行

**Comment by BryceAndJuly** [comment]
样式这个东西你可以自定义嘛。嵌入白板的文档，其对应的CSS文件就放在`Whiteboard/theme/theme.css`。
我自己用的里面就有一个深色主题的`theme.css`，你可以解压后替换试试，或者你自己改一个。
[theme.zip](https://github.com/user-attachments/files/17265727/theme.zip)
![深色主题](https://github.com/user-attachments/assets/c7ca600e-85b6-417d-ae15-74b97c1202ad)

**Comment by DIDAO123** [comment]
谢谢大佬，替换后能够实现黑色了。但是来回替换太麻烦了，能否有更便捷的切换方法在下一个版本提供。或者在思源设置外观那里加入什么css代码开启能够实现深色模式，关闭就是默认的浅色

**Comment by BryceAndJuly** [comment]
[Whiteboard.zip](https://github.com/user-attachments/files/17268503/Whiteboard.zip)
这个跟CSS片段没啥关系，弄个尝鲜版给你试试吧。这个是基于V1.3.3微调的，我试过是可以根据白板当前模式（深色/浅色）来调节嵌入文档的主题的。如果没生效，那就是需要保存后，点一下【刷新】或者直接关闭白板后重新打开。
集市那个刚更新完，先不更了，晚些时候再说吧。

https://github.com/user-attachments/assets/3e26a6ad-4d97-4a1d-bae2-36f86a8291a7

**Comment by DIDAO123** [comment]
谢谢大佬，用上了
