### ISSUE TITLE
手写笔字迹优化请求

### ISSUE THREAD

**Issue by pisceswb** [BryceAndJuly/Whiteboard#34]
大佬您好，发现页面放大后书写字迹的过度平滑化，可能与书写末尾直线段的长度有关（请看录屏），请问“书写末尾直线段”的长度能调节吗，或能否使其随着页面缩放变化，谢谢！

https://github.com/user-attachments/assets/1cd21bdb-9baa-47cd-8a24-aadd0c10d1e0

**Comment by pisceswb** [comment]
或将“书写末尾直线段”的长度与线的粗细进行关联

**Comment by BryceAndJuly** [comment]
手写方面的东西我是真的不了解，要不你去问问Excalidraw的作者吧。
[https://github.com/excalidraw/excalidraw/issues](https://github.com/excalidraw/excalidraw/issues)

**Comment by pisceswb** [comment]
好像大家对手写笔的优化都没有兴趣🤣
