### ISSUE TITLE
能否为whiteboard文档固定一个特定的图标，以与普通文档区别开来

### ISSUE THREAD

**Issue by pisceswb** [BryceAndJuly/Whiteboard#35]
如题，感觉创建whiteboard后，将文档图标默认修改为一个特殊图标，与普通文档能够区别开，比较好

**Comment by BryceAndJuly** [comment]
没必要，默认图标就行。反正文档图标能自定义，用户爱设置啥就啥呗。至于跟其它文档的区分，白板会自动设置别名，通过别名已经可以区分开了。

**Comment by pisceswb** [comment]
请问能给出一种能实现的方法吗？非常感谢！ @BryceAndJuly

**Comment by BryceAndJuly** [comment]
这个我没有写过，但是我看文档设置图标时的请求，用的应该是这个API。

## API

```json
/api/attr/setBlockAttrs
```

## 请求参数

```json
{
    "id": "20241008203015-iohemmg",
    "attrs": {
        "icon": "1f33f"
    }
}
```

其中`id`是文档的ID值，`icon`的值可以自定义成自己需要的图标。
