### ISSUE TITLE
请问铅笔手写字迹的粗细，能否不随页面的缩放而改变

### ISSUE THREAD

**Issue by pisceswb** [BryceAndJuly/Whiteboard#36]
请问能否绝对固定笔的粗细数值，使其不随页面的缩放而改变粗细，谢谢！

**Comment by BryceAndJuly** [comment]
那些手绘、箭头、图形都是画在同一个canvas画布上的，画布放大/缩小，然后画布上的字随之放大/缩小，这不是很正常吗？

**Comment by pisceswb** [comment]
手写字迹不缩放是为了增加手写体验，不然画布放大或缩小，需要重新调整画笔的粗细。

**Comment by pisceswb** [comment]
将您给出的调整画笔粗细的修改内容中，除以或乘以画布的缩放倍数即可，请问您能否给出该值的哪个，谢谢！！

**Comment by BryceAndJuly** [comment]
现在不知道，有空看看吧

**Comment by BryceAndJuly** [comment]
刚刚试了一下，在这个修改画笔粗细部分所在的函数里，好像不能直接访问到当前缩放比例的值。
你还是调整到合适比例再书写吧。
