### ISSUE TITLE
不能交互编辑吗

### ISSUE THREAD

**Issue by hibicious** [BryceAndJuly/Whiteboard#37]
在白板中拖入了一个块,鼠标放到块中间出现"点击开始交互",鼠标变成了输入状态下的鼠标,单数没有看淡光标闪动,不能在白板里面编辑块内容
![image](https://github.com/user-attachments/assets/de5f554d-fe4b-43aa-9d1f-32f38db8d58b)

**Comment by BryceAndJuly** [comment]
对，它现在只是单向获取块的内容并展示在白板上，并不能双向编辑，挂件说明里有写。
点击交互里的交互，现在是指页面滚动、链接点击、文本选中而已，并不包括编辑。
![说明](https://github.com/user-attachments/assets/4ba52d78-959e-4304-adea-2757fef9c49e)
