### ISSUE TITLE
点击块链接回到文档位置,在原来的块中修改了内容,但是在白班中需要手动刷新才可以显示出来.可不可自动同步而无需手动刷新

### ISSUE THREAD

**Issue by hibicious** [BryceAndJuly/Whiteboard#38]
![image](https://github.com/user-attachments/assets/eaca59c0-698c-4be8-82a6-da9c8e696559)

**Comment by BryceAndJuly** [comment]
现在的刷新是重载整个挂件而不是单独更新那个嵌入的Iframe文档，这种刷新还是手动处理吧。
