### ISSUE TITLE
思源和白板都是夜间模式,拖入一个块进白板,背景色缺失白色的,很不协调,可不可以做个适配,将背景色换成深色

### ISSUE THREAD

**Issue by hibicious** [BryceAndJuly/Whiteboard#39]
![image](https://github.com/user-attachments/assets/5891a3fb-b64b-4633-8294-3a14692d7493)

**Comment by BryceAndJuly** [comment]
这个好像有人问过了，就是[issue33](https://github.com/BryceAndJuly/Whiteboard/issues/33)，下个版本会加上。
