### ISSUE TITLE
macOS 版本的 Bug

### ISSUE THREAD

**Issue by entps** [BryceAndJuly/Whiteboard#4]
1. 主界面上的 【保存】 按钮无效；
2. 在文件中插入 Excalidraw 挂件后，打开文档时直接显示Excalidraw绘图编辑界面，，无法显示原文件的内容

**Comment by BryceAndJuly** [comment]
1、这个，应该是因为还没适配，按键有点不一样，先到集市卸载这个挂件吧。主要是我手上只有Windows本，我试着适配一下吧。
2、挂件默认就是铺满文档的，集市那里写的很清楚。已经插入挂件也不要太担心，你到集市里卸载掉这个挂件，然后重新打开这个文档，就可以删除掉那个挂件元素了。

**Comment by BryceAndJuly** [comment]
晚上会发个修复的版本，到时候看还有没有这个问题。先关了
