### ISSUE TITLE
请求添加嵌入网页

### ISSUE THREAD

**Issue by hibicious** [BryceAndJuly/Whiteboard#40]
![image](https://github.com/user-attachments/assets/2d065285-d1f3-4d2f-bc2e-5f03878094d6)

**Comment by BryceAndJuly** [comment]
你可以先自己改动一下来实现这个网页嵌入。


打开`Whiteboard/assets/index-c894b550.js`

搜索

```js
if(e.startsWith("siyuan://blocks/"))return!0;
```

替换成：

```js
if(e.startsWith("siyuan://blocks/"))return!0;if(e.startsWith("https://"))return!0;
```


搜索

```js
scrolling:"no",
```

替换成：

```js
scrolling:"yes",
```


修改完后保存，然后清一下缓存或者重启一下笔记软件，应该就能生效。效果差不多就是以下这样：

https://github.com/user-attachments/assets/137bce1f-bfba-4cd4-a75b-197625da83c8
