### ISSUE TITLE
希望素材库内容一直存在;增加素材库整理功能

### ISSUE THREAD

**Issue by hibicious** [BryceAndJuly/Whiteboard#41]
![image](https://github.com/user-attachments/assets/2ec47165-6ab2-403c-aa44-29a883d1ef12)
导入素材以后,重启思源,素材库内容就被清空了.已经导入的内容可以一直存在,不必每次重新导入.另外,希望出一个素材库整理功能,素材太多时,可以新建文件夹进行分类,以便于更快找到所需素材

**Comment by BryceAndJuly** [comment]
这个在说明文档里有写，还是有必要在使用前看一下的。素材库应该不会动了，基本就是保持Excalidraw原本的样子，就当一个离线版的Excalidraw来用。
![文档](https://github.com/user-attachments/assets/6daf7735-0016-4bec-9e65-9dc18c89884d)

**Comment by hibicious** [comment]
刚下载的时候文档全看过了,也配置了.就不久才发现想着添加素材库.原来是我的安装路径有中文,导致我的设置失效.我重新安装之后就可以了.
