### ISSUE TITLE
Allow internationalization for button texts and alerts

### ISSUE THREAD

**Issue by FROSADO** [BryceAndJuly/Whiteboard#42]
Please, Allow internationalization for button texts and alerts. 
The usage of Siyuan on English, excalidraw appear on English but some messages and buttons appear on Chinese.

**Comment by FROSADO** [comment]
#43 merge request created

**Comment by BryceAndJuly** [comment]
仓库已更新：
[https://github.com/BryceAndJuly/Whiteboard/commit/90cba8fe496608b23a754e5ec50020ccab8f26e4](https://github.com/BryceAndJuly/Whiteboard/commit/90cba8fe496608b23a754e5ec50020ccab8f26e4)
