### ISSUE TITLE
思源笔记白板挂件开发请求的反馈

### ISSUE THREAD

**Issue by daoyepro** [BryceAndJuly/Whiteboard#44]
第一：思源笔记中的白板挂件的文字颜色是否可以再丰富一些？目前颜色太少了，不够用。
第二：是否可以增加形状图的自动绘制？！比如三角形，菱形等，一笔可绘画出来。
暂时就这两个问题，谢谢。

**Comment by BryceAndJuly** [comment]
* 文字颜色除了放出来的那些颜色，还可以自定义颜色的十六进制值，甚至可以手动取色，颜色已经很丰富了。当然，为了使用时更方便，你可以把常用的不同颜色的文字添加到素材库，这样可以快速拖拽使用。
* 菱形在顶栏本来就有，至于三角形，可以自己绘制。常用的图形可以添加到素材库，这样用起来比临时绘制方便一点。

https://github.com/user-attachments/assets/38b3c815-3f87-418a-b27b-e450d3e5bf25

**Comment by daoyepro** [comment]
谢谢你的解答与视频讲解，顺便请教下，取色板在有链接吗？

**Comment by BryceAndJuly** [comment]
![色卡图](https://github.com/user-attachments/assets/10ec0135-c9f9-405a-b8fe-5f33d943139c)
