### ISSUE TITLE
如何修改内置的中文字体？

### ISSUE THREAD

**Issue by vipyanzg** [BryceAndJuly/Whiteboard#45]
如何修改内置的中文字体？想自己换一个中文手写字体。

**Comment by BryceAndJuly** [comment]
中文字体文件的路径：Whiteboard/Virgil.woff2

**Comment by 753769554** [comment]
![Image](https://github.com/user-attachments/assets/1f8a066a-2577-484e-9970-1b82a3bbd7fb)

我想修改默认的中文字体
请问具体怎么操作呢
把这个，中文字体文件的路径：Whiteboard/Virgil.woff2，这个文件删除了换成自己想要换的中文字体就可以嘛

是否需要动哪里的css代码

**Comment by BryceAndJuly** [comment]
之前回复的时候，挂件版本<=`1.6.0`（对应Excalidraw的版本是：`V0.17.0`），直接替换Virgil.woff2这个字体文件是可以的。

现在挂件最新版本是`V2.0.5`（对应Excalidraw的版本是`V0.18.0`）,官方已经自带了手写字体，而且对字体进行了拆分以便懒加载，不好直接换字体文件了。

[[Adding hand-drawn font for Chinese, Japanese and Korean to Excalidraw](https://plus.excalidraw.com/blog/adding-hand-drawn-font-for-chinese-japanese-korean)](https://plus.excalidraw.com/blog/adding-hand-drawn-font-for-chinese-japanese-korean)

<img width="1242" alt="Image" src="https://github.com/user-attachments/assets/0c6c9aef-be9d-4d47-8e8f-1f6006eec830" />
