### ISSUE TITLE
文本框不能左右或上下调节大小

### ISSUE THREAD

**Issue by laofan888** [BryceAndJuly/Whiteboard#46]
excalidraw官网上的文本框是能左右或上下调节大小的，但思源这里没法儿办到。
就会导致：比如在同一行写了很多字，只能横向延伸了，没法儿自动换行……
谢谢~~

**Comment by BryceAndJuly** [comment]
复现不了。

https://github.com/user-attachments/assets/b76999fe-f11a-46e7-8f94-1b4ebbc412b3

**Comment by laofan888** [comment]
问题出在纯文本框上（不是图形）。

https://github.com/user-attachments/assets/90278975-4a99-4d07-81be-3bdfd5fd4a7e


https://github.com/user-attachments/assets/0362d77f-116d-4b57-b124-0dff4b54506c

**Comment by laofan888** [comment]
问题出在纯文本框上（而不是图形）。

https://github.com/user-attachments/assets/f183dbae-67ed-4196-aeb6-ce1552611430


https://github.com/user-attachments/assets/63a4a085-f7ac-4553-b730-2710cc529b7c

**Comment by BryceAndJuly** [comment]
哦，看到了。24年5月1号提交的特性，但Excalidraw最新发布版本还停留在2月9号。而且这也不是什么特别影响使用的特性，矩形框就可以自动换行，也可以设置透明边框。暂时不考虑改动了。
[feat: resize elements from the sides](https://github.com/excalidraw/excalidraw/pull/7855/files)

![最新发布版本](https://github.com/user-attachments/assets/621569cd-f57a-461a-af37-bd042fcb2bf2)

**Comment by laofan888** [comment]
好的，明白了。谢谢哈
