### ISSUE TITLE
新窗口中，按键问题

### ISSUE THREAD

**Issue by pisceswb** [BryceAndJuly/Whiteboard#5]
在思源笔记2.12.0版本中，使用移动到新窗口功能，在单独窗口显示whiteboard页面。中间上方的按键只有下部分能够正常点击，上面的部分好像属于标题栏了，按住鼠标能够拖动窗口位置，不能点击选择工具。请问能否优化一下，谢谢！
![whiteboard](https://github.com/BryceAndJuly/Whiteboard/assets/104658457/907ca6b0-9b14-467e-8407-b91cf451dcf1)

**Comment by BryceAndJuly** [comment]
没复现这个问题，你换默认主题再试试。

https://github.com/BryceAndJuly/Whiteboard/assets/58081876/24e9774a-5cdd-4d72-8fcc-330276b7e997

**Comment by pisceswb** [comment]
找到原因了，是一个叫小窗的插件，将标题栏隐藏了，将其卸载后就正常了。不是whiteboard的原因
