### ISSUE TITLE
能否在白板中嵌入块呢？

### ISSUE THREAD

**Issue by mozhux** [BryceAndJuly/Whiteboard#7]
如题，目前可以挂件嵌入文档了，但是文档还不能嵌入白板中。插件中td白板已经支持，后续有没有可能支持一下？
![image](https://github.com/BryceAndJuly/Whiteboard/assets/46953371/cfa186de-3353-41e6-9a26-658948b80826)
![image](https://github.com/BryceAndJuly/Whiteboard/assets/46953371/0ff737ec-e70b-4887-8d20-d58b09edec71)

**Comment by BryceAndJuly** [comment]
嵌入块的话，刚刚看了一下，Tldraw白板往里放了个div的节点。Excalidraw我看它画布那部分是Canvas画的，目前还不知道如何能在里面混入一个HTML节点作为元素。
我看到【Tldraw白板插件】跟【Excalidraw插件】的作者是同一个人，感觉这位大佬可能有办法，就是不知道他有没有空给【Excalidraw插件】加这个功能。你可以先去【Excalidraw插件】那里提一下。
![截图](https://github.com/BryceAndJuly/Whiteboard/assets/58081876/13a5c052-a42e-47f5-ae7d-02ec17769ca8)

**Comment by BryceAndJuly** [comment]
这个挂件的Excalidraw版本可能有点旧了，官网最新版的看着有Iframe的元素，到时候有时间可以研究一下。
![最新版](https://github.com/BryceAndJuly/Whiteboard/assets/58081876/8ec18f2e-7bfe-4e98-aa48-eeb350585014)

**Comment by mozhux** [comment]
> 这个挂件的Excalidraw版本可能有点旧了，官网最新版的看着有Iframe的元素，到时候有时间可以研究一下。 ![最新版](https://private-user-images.githubusercontent.com/58081876/294229492-8ec18f2e-7bfe-4e98-aa48-eeb350585014.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MTQ2ODcsIm5iZiI6MTcwNDQxNDM4NywicGF0aCI6Ii81ODA4MTg3Ni8yOTQyMjk0OTItOGVjMThmMmUtN2JmZS00ZTk4LWFhNDgtZWViMzUwNTg1MDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDAwMjYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMGNlZmViZjIwOGI0ZDg2YjI2MGY1ODIyY2Q4MmJkNTkyZjE5MGQ5ZmJkYzgwZjc3OTE3NWM0N2RkMjgzYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lmKYy8-yq5sU1vw9UbuB0SU1YQ7RhkxbPzpIDIc_rys)

我觉得行，Z佬那个可能主要研究td白板去了。

**Comment by BryceAndJuly** [comment]
试着嵌入了几个，感觉性能很差，再多几个的时候移动白板就容易卡顿了，不知道是版本问题还是哪里没处理好，要做到流畅可用的话估计太费时间了，我还是期待一下官方的白板吧。这个暂时不做了。

https://github.com/BryceAndJuly/Whiteboard/assets/58081876/ed556e9e-e347-4d58-a7c1-5b3b88bc2c8d

**Comment by mozhux** [comment]
> 试着嵌入了几个，感觉性能很差，再多几个的时候移动白板就容易卡顿了，不知道是版本问题还是哪里没处理好，要做到流畅可用的话估计太费时间了，我还是期待一下官方的白板吧。这个暂时不做了。
> 
>  iframe.mp4

官方白板应该是难等了，或者说会很久。确实，ob那边都是完全魔改才有那种效果。

**Comment by BryceAndJuly** [comment]
@mozhux 刚改了个新版本V1.0.8，能嵌入笔记内普通的文档/块，但是还不能编辑，你可以试试看。

**Comment by mozhux** [comment]
> @mozhux 刚改了个新版本V1.0.8，能嵌入笔记内普通的文档/块，但是还不能编辑，你可以试试看。

感谢，已经用上。整体已基本满足需求了，就是这个嵌入网页，应该也是可以嵌入外部网页的吧？不建议限制这个呢。ob上那个ex插件应该是都支持了，也是开源的，不知道能不能借鉴。
![image](https://github.com/BryceAndJuly/Whiteboard/assets/46953371/74ba31c6-6a8d-4049-b291-ffb1e29a573d)
另外就是交互看后面有没有时间再优化一下，点击开始交互才能操作感觉上还是有点别扭，还希望能显示一下文档标题如果有的话。

**Comment by mozhux** [comment]
还发现一个不知道什么问题。如果把白板以嵌入块的方式放到别的文档，导出那个文档，会发生冲突有点覆盖。
![image](https://github.com/BryceAndJuly/Whiteboard/assets/46953371/0e427f81-3322-4c13-8169-6f9460565f02)
![image](https://github.com/BryceAndJuly/Whiteboard/assets/46953371/a1ca6169-2127-44bc-ab90-2fdf5951bfc4)

**Comment by BryceAndJuly** [comment]
那个插件的仓库我还没了解过，这个是直接用Excalidraw发布的0.17.0版本改的，那个网址白名单是它默认的，那部分我没改，你用那个在线的Excalidraw就知道了。

那个白板嵌入块的话，平时看看还可以，要导出的时候，最好别用白板的嵌入块形式，而是手动复制白板为PNG，然后粘贴到文档里。

**Comment by mozhux** [comment]
> 那个插件的仓库我还没了解过，这个是直接用Excalidraw发布的0.17.0版本改的，那个网址白名单是它默认的，那部分我没改，你用那个在线的Excalidraw就知道了。
> 
> 那个白板嵌入块的话，平时看看还可以，要导出的时候，最好别用白板的嵌入块形式，而是手动复制白板为PNG，然后粘贴到文档里。

好的，已经很不错了，嵌入块我还是少用

**Comment by BryceAndJuly** [comment]
至于那个【点击交互】是它原来的设定，那部分的源码我还没看，有空再看看吧。
