### ISSUE TITLE
建议：上一版本按F键可进全屏，升级后F键变成了Frame，如果可以增加一个全屏快捷键会更好，现在不单没全屏快捷键，连右键菜单的全屏也没有了

### ISSUE THREAD

**Issue by entps** [BryceAndJuly/Whiteboard#8]
建议：上一版本按F键可进全屏，升级后F键变成了Frame，如果可以增加一个全屏快捷键会更好，现在不单没全屏快捷键，连右键菜单的全屏也没有了

**Comment by BryceAndJuly** [comment]
哦，这个是人家Excalidraw原仓库的更改，就是在V0.17.0这个版本改的。增加一个全屏快捷键的话周末试试吧，到时候看有没有副作用，有副作用的话就不加了。

[https://github.com/excalidraw/excalidraw/releases](https://github.com/excalidraw/excalidraw/releases)；
![新版删掉全屏按钮](https://github.com/BryceAndJuly/Whiteboard/assets/58081876/a1bae962-e58e-4370-938e-ab199f9e857d)
![merged](https://github.com/BryceAndJuly/Whiteboard/assets/58081876/3b11506e-d0f7-41b4-9c1d-f9ffd0bfbefd)

**Comment by entps** [comment]
macOS 升级，全屏后不能退出



在 2024年1月27日 ***@***.***> 写道：


Closed #8 as completed.

**Comment by entps** [comment]
具体问题表现：(macOS)




1. 点击 Excalidraw 绘图界面空白处，用 Option + Y 无法全屏
2. 点击 侧边栏空白处，用 Option + Y 可以全屏
3. 全屏后由于鼠标操作了绘图，焦点在 Excalidraw 里，，用 Option + Y 无法退出全屏，，同时全屏时无法激活侧边栏焦点，所以无法退出全屏，，只能强制退出思源笔记




总结：  当 Excalidraw 绘图获得焦点时，无法用  Option + Y 全屏或退出全屏
           当 侧边栏获得焦时时，可以用 Option + Y 全屏或退出全屏


在 2024年1月27日 ***@***.***> 写道：


Closed #8 as completed.

**Comment by BryceAndJuly** [comment]
哦，那可能是快捷键没兼容MacOS，那就先别用全屏功能了，等改版后再试。

**Comment by BryceAndJuly** [comment]
不对呀，在MacOS上按Option键，跟在Windows上按Alt键都会激活event.altKey啊，是不是没清掉缓存，白板加载的还是上一版的？

要不你先清一下缓存再试试。

点击笔记右下角的`？`帮助按钮——【开发者工具】——【Network】——勾选下方的【Disable cache】——按`F5`刷新——刷新后取消勾选【Disable cache】
![清除缓存](https://github.com/BryceAndJuly/Whiteboard/assets/58081876/bab786f5-8349-4ccc-954c-b8fa21b97ea3)

**Comment by entps** [comment]
抱歉，测试过，不行，，Excalidraw 铺满文档区时，，按 Option 可能激活不了 event.altKey，，在刷新按钮前先回个全屏，，先实现可以通过按钮实现全屏，，之后再解决快捷键的问题。



在 2024年1月27日 ***@***.***> 写道：


不对呀，在MacOS上按Option键，跟在Windows上按Alt键都会激活event.altKey啊，是不是没清掉缓存，白板加载的还是上一版的？
要不你先清一下缓存再试试。
点击笔记右下角的？帮助按钮——【开发者工具】——【Network】——勾选下方的【Disable cache】——按F5刷新——刷新后取消勾选【Disable cache】
 default.png (view on web)

**Comment by BryceAndJuly** [comment]
按文档来说是激活的，但暂时没有实体的Mac设备来调试，Windows上全屏这个是没问题的，试试到集市卸载后再安装一下吧，要是还不行那就真不行了。
![altKey](https://github.com/BryceAndJuly/Whiteboard/assets/58081876/d6f57ead-8271-4428-9a41-9b24f9dd60d6)

https://github.com/BryceAndJuly/Whiteboard/assets/58081876/ee85bdf9-45c8-44b2-8ad0-82f3ea3c1ad0

**Comment by entps** [comment]
谢谢，幸苦了！全屏能有最好，没有也不太影响使用。




焦点在 1、2 可以通过 Option + Y 进入/退出全屏
焦点在 3 则失效


在 Windows 则正常，，但用鼠标点击 Excalidraw 上面的工具按钮时，，，正中是点不了的，，鼠标要偏下，点按钮的下 三分一 才可以点，，这是不是属性位置偏移的情况。


在 2024年1月28日 ***@***.***> 写道：


按文档来说是激活的，但暂时没有实体的Mac设备来调试，Windows上全屏这个是没问题的，试试到集市卸载后再安装一下吧，要是还不行那就真不行了。
 altKey.png (view on web)
https://github.com/BryceAndJuly/Whiteboard/assets/58081876/ee85bdf9-45c8-44b2-8ad0-82f3ea3c1ad0

**Comment by BryceAndJuly** [comment]
全屏的时候，点击工具按钮要往下一点是因为笔记软件的顶栏有个拖拽窗口的条，笔记小窗口的时候双击这个拖拽条还可以让笔记窗口全屏。你要实在看着它难受的话，可以用CSS片段把它属性改一下，改完之后就可以白板顶栏按钮正常点了，但是平时就拖拽不了了。不建议你折腾这个，其实收起边栏的话，白板区域也不小了，你按自己需求来吧。
```js
.toolbar #drag {
    -webkit-app-region: inherit !important;
}
```

**Comment by entps** [comment]
好的，谢谢，，我退回 1.0.7 版本使用了，，，这个版本最好用，，，新版虽然多了 嵌入文档和激光笔等功能，但基本用不上




在 2024年1月28日 ***@***.***> 写道：


全屏的时候，点击工具按钮要往下一点是因为笔记软件的顶栏有个拖拽窗口的条，笔记小窗口的时候双击这个拖拽条还可以让笔记窗口全屏。你要实在看着它难受的话，可以用CSS片段把它属性改一下，改完之后就可以白板顶栏按钮正常点了，但是平时就拖拽不了了。不建议你折腾这个，其实收起边栏的话，白板区域也不小了，你按自己需求来吧。
.toolbar #drag { -webkit-app-region: inherit !important; }
